export const notesPo = {
  box: () => cy.get('pk-notes'),
  header: () => cy.get('pk-notes header'),
  actions: () => cy.get('pk-notes header .main-box-actions button'),
  closeBtn: () => cy.get('pk-notes header button[mattooltip="Close"]'),
  addNoteBtn: () => cy.get('pk-notes header button[mattooltip="Add note"]'),
  noteCards: () => cy.get('pk-note-card'),
  noteCard: (i: number) => cy.get('pk-note-card mat-card').eq(i),
  noteLinks: (i: number) => cy.get(`pk-note-card:nth-of-type(${i + 1}) mat-card .links li`),
  editBtn: (i: number) => cy.get('pk-note-card mat-card footer button:nth-child(1)').eq(i),
  pinBtn: (i: number) => cy.get('pk-note-card mat-card footer button:nth-child(2)').eq(i),
  archiveBtn: (i: number) => cy.get('pk-note-card mat-card footer button:nth-child(3)').eq(i),
  deleteBtn: (i: number) => cy.get('pk-note-card mat-card footer button:nth-child(4)').eq(i),
  noteDialog: {
    dialog: () => cy.get('pk-note-dialog'),
    title: () => cy.get('pk-note-dialog h1'),
    closeBtn: () => cy.get('pk-note-dialog .mat-dialog-actions button:first-child'),
    saveBtn: () => cy.get('pk-note-dialog .mat-dialog-actions button:last-child'),
    textField: () => cy.get('pk-note-dialog textarea[formcontrolname="text"]'),
    addLinkBtn: () => cy.get('pk-note-dialog button').contains('Add link'),
    linkNameInput: () => cy.get('pk-note-dialog input[formcontrolname="name"]'),
    linkUrlInput: () => cy.get('pk-note-dialog input[formcontrolname="url"]'),
  },
}
