export const shortcutsPo = {
  menu: () => cy.get('pk-shortcuts-menu .shortcuts-menu'),
  menuButtons: () => cy.get('pk-shortcuts-menu button'),
  menuButton: (i: number) => cy.get('pk-shortcuts-menu button').eq(i),
  backdrop: () => cy.get('pk-shortcuts .shortcuts-backdrop'),
  shortcuts: () => cy.get('pk-shortcut'),
  shortcut: (i: number) => cy.get('pk-shortcut button').eq(i),
  shortcutContextMenu: () => cy.get('.shortcut-context-menu'),
  shortcutContextMenuButtons: () => cy.get('.shortcut-context-menu button'),
  editShortcutBtn: () => cy.get('.shortcut-context-menu button:first-child'),
  deleteShortcutBtn: () => cy.get('.shortcut-context-menu button:last-child'),
  addContextMenu: () => cy.get('.add-shortcut-context-menu'),
  addShortcutBtn: () => cy.get('.add-shortcut-context-menu button').contains('Add shortcut'),
  shortcutDialog: {
    dialog: () => cy.get('pk-shortcut-dialog'),
    title: () => cy.get('pk-shortcut-dialog h1'),
    nameInput: () => cy.get('pk-shortcut-dialog input[formcontrolname="name"]'),
    urlInput: () => cy.get('pk-shortcut-dialog input[formcontrolname="url"]'),
    iconUrlInput: () => cy.get('pk-shortcut-dialog input[formcontrolname="iconUrl"]'),
    categoryInput: () => cy.get('pk-shortcut-dialog mat-select[formcontrolname="category"]'),
    priorityInput: () => cy.get('pk-shortcut-dialog mat-slider[formcontrolname="priority"]'),
    closeBtn: () => cy.get('pk-shortcut-dialog .mat-dialog-actions button:first-child'),
    saveBtn: () => cy.get('pk-shortcut-dialog .mat-dialog-actions button:last-child'),
  },
}
